name: Exe Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+_cio'
    branches:
      - 'commandio'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx (non-Windows)
      if: runner.os != 'Windows'
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry (non-Windows)
      if: runner.os != 'Windows'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Docker version (non-Windows)
      if: runner.os != 'Windows'
      id: docker-version
      run: |
        echo "version=$(python scripts/docker_version.py)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Check if Docker image exists (non-Windows)
      if: runner.os != 'Windows'
      id: check-image
      run: |
        if docker manifest inspect ghcr.io/${{ github.repository }}/builder:${{ steps.docker-version.outputs.version }}-${{ runner.os }} > /dev/null 2>&1; then
          echo "image_exists=true" >> $GITHUB_OUTPUT
        else
          echo "image_exists=false" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Build and push Docker image (non-Windows)
      if: steps.check-image.outputs.image_exists != 'true' && runner.os != 'Windows'
      uses: docker/build-push-action@v5
      with:
        context: .
        file: scripts/Dockerfile.linux.cio
        push: true
        tags: ghcr.io/${{ github.repository }}/builder:${{ steps.docker-version.outputs.version }}-${{ runner.os }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Set up Python (Windows)
      if: runner.os == 'Windows'
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pyinstaller
      shell: bash

    - name: Build Release (non-Windows)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/repo \
          -v ${{ github.workspace }}/dist:/repo/dist \
          ghcr.io/${{ github.repository }}/builder:${{ steps.docker-version.outputs.version }}-${{ runner.os }}

    - name: Build Release (Windows)
      if: runner.os == 'Windows'
      shell: bash
      run: |
        python scripts/build.py

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: release-${{ runner.os }}
        path: dist/*

  create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/**/*
        generate_release_notes: true
